.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. heptafranc_qt test_heptafranc_qt
clean: FORCE
	$(MAKE) -C .. heptafranc_qt_clean test_heptafranc_qt_clean
check: FORCE
	$(MAKE) -C .. test_heptafranc_qt_check
heptafranc-qt heptafranc-qt.exe: FORCE
	 $(MAKE) -C .. heptafranc_qt
